export enum Delatnost {
    ODBRANA = 'ODBRANA',
    EKONOMSKI_I_FINANSIJSKI_ODNOSI = 'EKONOMSKI_I_FINANSIJSKI_ODNOSI',
    EDUKACIJA = 'EDUKACIJA',
    OPSTE_JAVNE_USLUGE = 'OPSTE_JAVNE_USLUGE',
    ZDRAVSTVO = 'ZDRAVSTVO'
}